declare enum RequestError {
    NETWORK_ERROR = "NETWORK_ERROR",
    BAD_RESPONSE = "BAD_RESPONSE",
    SESION_EXPIRED = "SESION_EXPIRED",
    ACCESS_DENIED = "ACCESS_DENIED",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    VALIDATION_FAILED = "VALIDATION_FAILED",
};
